name: github repository dispatch shell action
description: github repository dispatch shell action
author: RekGRpth
runs:
  using: composite
  steps:
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
