name: github repository dispatch action
description: github repository dispatch action
author: RekGRpth
inputs:
  client-payload:
    description: github repository dispatch client payload
    default: '{}'
  event-type:
    description: github repository dispatch event type
    required: true
  repository:
    description: github repository dispatch repository
    default: ${{ github.repository }}
  token:
    description: github repository dispatch token
    required: true
runs:
  using: composite
  steps:
    - run: |
        set -eux
        export INPUTS_DATA='{"event_type": "${{ inputs.event-type }}", "client_payload": ${{ inputs.client-payload }}}'
        export INPUTS_REPOSITORY="${{ inputs.repository }}"
        export INPUTS_TOKEN="${{ inputs.token }}"
        "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
