name: github repository dispatch action
description: github repository dispatch action
author: RekGRpth
runs:
  using: composite
  steps:
    - run: echo "${{ toJSON(github) }}"
      shell: sh
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
