name: Release
on:
  push:
    branches:
      - ${{ github.event.branch }}
  workflow_dispatch:
jobs:
  release:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: .github/workflows/release.sh
