name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            set -eux
            hub release delete master
            hub release create --message ${{ github.event.head_commit.message }} master
