name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: hub release edit --message "${{ github.event.head_commit.message }}" v1
        shell: sh
