name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rekgrpth/git-clone-action@v1
      - run: hub release create v1
