name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: echo "${{ toJSON(github) }}"
      - uses: rekgrpth/git-clone-action@v1
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: hub release delete v1 || echo "$?"
        shell: sh
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: hub release create --message "${{ github.event.head_commit.message }}" v1
        shell: sh
