name: Release
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  release:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: echo "${{ toJSON(github) }}"
      - run: hub api "repos/${{ github.repository }}/releases/tags/v1" | jq .
      - run: hub api --method DELETE "repos/${{ github.repository }}/releases/$(hub api "repos/${{ github.repository }}/releases/tags/v1" | jq .id)"
      - run: hub api "repos/${{ github.repository }}/releases" --field tag_name=v1 | jq .
